#!/usr/bin/env bash

confDir="${confDir:-$HOME/.config}"
gtkIcon="${gtkIcon:-Tela-circle-dracula}"
iconsDir="${iconsDir:-$XDG_DATA_HOME}/icons"
cacheDir="${cacheDir:-$XDG_CACHE_HOME}"
wallbashScripts="${wallbashScripts:-$hydeConfDir/wallbash/scripts}"
hypr_border=10
dunstDir="${confDir}/dunst"
allIcons=$(find "${XDG_DATA_HOME:-$XDG_DATA_HOME}/icons" -mindepth 1 -maxdepth 1 -type d ! -name '*ursor*' -printf '%f,' | sed 's/,$//' | head -n 20)

# regen conf
cat <<WARN >"${dunstDir}/dunstrc"
# WARNING: This file is auto-generated by '${wallbashScripts}/dunst.sh'.
# DO NOT edit manually.
# For user configuration edit '${confDir}/dunst/dunst.conf'


# HyDE specific section // Can be overridden by the configuration below
# ------------------------------------------------------------------------------
[global]
corner_radius = ${hypr_border}
icon_corner_radius = ${hypr_border}
icon_theme = "$gtkIcon,${allIcons}"
dmenu = $(which rofi) -config "${confDir}/rofi/notification.rasi" -dmenu -p dunst:

[Type-1]
appname = "t1"
format = "<b>%s</b>"

[Type-2]
appname = "t2"
format = "<span size="250%">%s</span>\n%b"

[urgency_critical]
background = "#f5e0dc"
foreground = "#1e1e2e"
frame_color = "#f38ba8"
icon = "${iconsDir}/Wallbash-Icon/critical.svg"
timeout = 0

# ------------------------------------------------------------------------------

WARN

# For Clarity We added a warning and remove comments and empty lines for the auto-generated file
grep -v '^\s*#' "${dunstDir}/dunst.conf" | grep -v '^\s*$' | envsubst >>"${dunstDir}/dunstrc"

mkdir -p "${cacheDir}/wallbash"
envsubst <"${cacheDir}/wallbash/dunst.conf" >>"${dunstDir}/dunstrc"
killall dunst
dunst &
