name: Bug report
description: Create a report to help us improve
title: "[Bug]: Short description of the issue"
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. First Step
        2. Second Step
        3. and so on...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please run this command to save your system information to a file:
        ```bash
        hyprctl systeminfo -c > /tmp/hyprland_systeminfo.txt
        ```
        Then copy the contents and paste them in the collapsible section below.

        Also include these additional details:
        - Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
        - Display Resolution: [e.g., 1920x1080]
        - Graphics Driver: [e.g., nvidia, intel, amd]
        - Display Server: [e.g., Wayland, X11]
      placeholder: |
        <details>
        <summary>System Information (Click to expand)</summary>
        ```
        [Paste the entire output of hyprctl systeminfo -c here]
        ```
        </details>
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
      placeholder: Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.
    validations:
      required: false
