#!/bin/env bash

scrDir="$(dirname "$(realpath "$0")")"
export scrDir
# shellcheck disable=SC1091
source "${scrDir}/globalcontrol.sh"
confDir="${confDir:-$XDG_CONFIG_HOME}"
hydeThemeDir="${hydeThemeDir:-$confDir/hyde/themes}"
hydeTheme="${hydeTheme:-}"
enableWallDcol="${enableWallDcol:-}"

# Validate the theme configuration file
cat <<WALLBASH >"${confDir}/hypr/themes/wallbash.conf"
# Auto-generated by HyDE // Read-only
# // ----------------------------
# HyDE Theme: ${hydeTheme}
# Configuration File: "${hydeThemeDir}/hypr.theme"
# Wallbash Mode : $(sed -e 's/^0$/theme/' -e 's/^1$/auto/' -e 's/^2$/dark/' -e 's/^3$/light/' <<<"${enableWallDcol}")
# // ----------------------------

\$HYDE_THEME=${hydeTheme}
\$GTK_THEME=$(get_hyprConf 'GTK_THEME')
\$ICON_THEME=$(get_hyprConf 'ICON_THEME')
\$COLOR-SCHEME=$(get_hyprConf 'COLOR_SCHEME')

\$CURSOR_THEME=$(get_hyprConf 'CURSOR_THEME')
\$CURSOR_SIZE=$(get_hyprConf 'CURSOR_SIZE')

\$FONT=$(get_hyprConf 'FONT')
\$FONT_SIZE=$(get_hyprConf 'FONT_SIZE')
\$DOCUMENT_FONT=$(get_hyprConf 'DOCUMENT_FONT')
\$DOCUMENT_FONT_SIZE=$(get_hyprConf 'DOCUMENT_FONT_SIZE')
\$MONOSPACE_FONT=$(get_hyprConf 'MONOSPACE_FONT')
\$MONOSPACE_FONT_SIZE=$(get_hyprConf 'MONOSPACE_FONT_SIZE')


\$CODE_THEME=$(get_hyprConf 'CODE_THEME')
\$SDDM_THEME=$(get_hyprConf 'SDDM_THEME')

# // ----------------------------
# README:
# Values above are derived and sanitized from the Configuration File,
# This is to ensure themes won't have any 'exec' or 'source'
# commands that could potentially harm the system
#  or undesired behavior.
#
# Dear Theme Owner:
# You can still add your own custom 'exec' or 'source' commands
#  by adding it as variable, examples (you can name the variable anything):
# Note that you should indicate it in your README.md
#
#
# -- ⌨️ theme.conf --
# \$RUN_CMD="some_command"
# \$SOURCE_FILE="/some/files"
#
#
# -- ⌨️ hyprland.conf --
# exec = \${RUN_CMD}"
# source = \${SOURCE_FILE}
# exec = Hyde code theme \$CODE_THEME # Setting the code theme

# // ----------------------------
WALLBASH